In [1]:
import numpy as np
import math as math
x=45
y=4.5
print(x)
print '$\omega$'

45
$\omega$


In [10]:
print (x+y)

49.5


In [2]:
a= True
print(a, type(a))
import numpy as np
import math as math
              

(True, <type 'bool'>)


This is a markdown cell $$x+y$$


Can't add numbers to strings 
to take suqare root: math.sqrt(....)
to find what is in a library, can type dir on it : print dir(...)


In [12]:
a=3
print a
d= True 
print type(d)
print math.sqrt(a)

3
<type 'bool'>
1.73205080757


In [13]:
# lists
lista= [1,2,3,4,5]
print lista[1]
print lista[-3]
print lista [0:5:1]
print lista[::2]
print lista[1:4:1]
listb= [0, 9, "2", "hi"]

2
3
[1, 2, 3, 4, 5]
[1, 3, 5]
[2, 3, 4]


Lists do have an order. they can contain different types as well. 
we can make dictionaries too


In [25]:
info= dict() # make an empty dictionary
info['name']= 'Joe'
info['weight']= 60.3#kg
# we are done filling in info
print info
print info.keys
print(info['name'], type(info['name']))
print info['weight']
# can use for loops
for key in info.keys():
    print (key, info[key], type(info[key]))

{'name': 'Joe', 'weight': 60.3}
<built-in method keys of dict object at 0x0000000003D9B598>
('Joe', <type 'str'>)
60.3
('name', 'Joe', <type 'str'>)
('weight', 60.3, <type 'float'>)


In [27]:
newinfo= info.copy()  # better than just equating. doesn't change info too
newinfo['weight']= 77.9
print (newinfo)
print (info)


{'name': 'Joe', 'weight': 77.9}
{'name': 'Joe', 'weight': 60.3}


In [24]:
array= np.array([[1,2,3,4,6,7,8], [0,0,0,0,0,0,0]])
print array
print np.shape(array)

[[1 2 3 4 6 7 8]
 [0 0 0 0 0 0 0]]
(2L, 7L)


In [17]:
if x>y:
    print "x is bigger"
else:
    print "y is bigger"

x is bigger


In [2]:
A=np.array([[1,3,2,5],[4,4,4,4]])
print A[1, 3]
print A[1:]
print A[-1:]
print A.T
b= np.array([2, 4])
#print b+A.T
# print A+b.T I guess this does not work- can't do (2, 4) and (2, )


4
[[4 4 4 4]]
[[4 4 4 4]]
[[1 4]
 [3 4]
 [2 4]
 [5 4]]


In [3]:
val=0 
for i in range(0,3):
    val=i-1
    